//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpID { get; set; }
        [Required]
        [MaxLength(32)]
        public string EmpName { get; set; }
        [Required]
        [MaxLength(50)]
        [EmailAddress]
        public string Email { get; set; }        
        [StringLength(500, MinimumLength=3)]
        public string Address { get; set; }
        [Required]
        [MaxLength(15)]
        public string Phone { get; set; }
    }
}
